# Generated by Django 5.2.7 on 2025-10-18 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modifier_group_name', models.CharField(blank=True, max_length=255)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=1)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group_modifier',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='goods.group')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Dish', 'Dish'), ('Modifier', 'Modifier')], default='Dish', max_length=20)),
                ('measure_unit', models.CharField(blank=True, max_length=50)),
                ('weight', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('payment_subject', models.CharField(default='ТОВАР', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_text', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_included_in_menu', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='goods.group')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='goods.productcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='GroupModifierChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_amount', models.IntegerField(default=0)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('hide_if_default_amount', models.BooleanField(default=False)),
                ('splittable', models.BooleanField(default=False)),
                ('free_of_charge_amount', models.IntegerField(default=0)),
                ('group_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.groupmodifier')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_children', to='goods.product')),
            ],
            options={
                'db_table': 'group_modifield_child',
            },
        ),
        migrations.AddField(
            model_name='groupmodifier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_modifiers', to='goods.product'),
        ),
    ]
