# Generated by Django 5.2.7 on 2025-10-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_deleted',
        ),
    ]
