# Generated by Django 5.2.7 on 2025-10-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_group_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
