# Generated by Django 5.2.7 on 2025-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='image_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_group_modifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_included_in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='seo_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
