# Generated by Django 5.2.7 on 2025-10-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_group_additional_info_group_code_group_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_deleted',
        ),
    ]
