# Generated by Django 5.2.7 on 2025-10-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_group_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
    ]
