# Generated by Django 5.2.7 on 2025-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_group_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
