# Generated by Django 5.1.4 on 2025-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_group_slug_product_slug_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit_ru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
