# Generated by Django 5.1.4 on 2026-01-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_product_additional_info_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='additional_info',
            new_name='additional_info_uk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='measure_unit',
            new_name='measure_unit_uk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_uk',
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
