# Generated by Django 5.1.4 on 2026-01-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_productsize_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
    ]
