# Generated by Django 5.1.4 on 2026-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_remove_product_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about_product_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_product_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_product_uk',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
