# Generated by Django 5.1.4 on 2026-01-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='address_en',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='address_ru',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_uk',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_ru',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_uk',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='goods.category'),
        ),
    ]
