# Generated by Django 5.1.4 on 2026-01-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_category_rename_address_restaurant_address_en_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
