# Generated by Django 5.1.4 on 2026-01-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
