# Generated by Django 5.1.4 on 2026-02-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відображати на сайті'),
        ),
    ]
