# Generated by Django 5.1.4 on 2026-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_product_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Dish', 'Dish'), ('Modifier', 'Modifier'), ('Service', 'Service')], default='Dish', max_length=20),
        ),
    ]
