# Generated by Django 5.1.4 on 2026-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manual_params',
            field=models.BooleanField(default=False, verbose_name='Редагувати вагу/розмір вручну (блокує оновлення з Syrve)'),
        ),
    ]
