# Generated by Django 5.1.4 on 2026-03-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_product_is_manual_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_included_in_menu',
        ),
    ]
