# Generated by Django 5.1.4 on 2026-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_remove_product_is_included_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Дата оновлення'),
        ),
    ]
