# Generated by Django 5.1.4 on 2026-02-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_type_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monobank_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
