# Generated by Django 5.1.4 on 2026-02-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_monobank_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', max_length=50, null=True),
        ),
    ]
