# Generated by Django 5.1.4 on 2026-03-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_alter_product_type'),
        ('orders', '0004_order_payment_method'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('WEB', 'Сайт'), ('LOKO', 'LOKO'), ('BOLT', 'BOLT'), ('GLOVO', 'GLOVO'), ('TG_BOT', 'Телеграм бот')], default='WEB', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='Адреса доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='terminal_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.restaurant', verbose_name='Локація'),
        ),
    ]
