# Generated by Django 5.1.4 on 2026-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_source_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('WEB', 'Сайт'), ('LOKO', 'LOKO'), ('BOLT', 'BOLT'), ('GLOVO', 'GLOVO'), ('TG_BOT', 'Телеграм бот')], default='WEB', max_length=10, verbose_name='Джерело'),
        ),
    ]
