# Generated by Django 5.1.4 on 2026-03-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('PENDING', 'ОЧІКУЄМО ОПЛАТУ'), ('PAID', 'ОПЛАЧЕНО'), ('COD', 'ОПЛАТА ПРИ ОТРИМАННІ')], default='COD', max_length=10, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordertype', verbose_name='Тип доставки'),
        ),
    ]
