# Generated by Django 5.1.4 on 2026-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_is_paid_alter_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ОЧІКУЄМО ОПЛАТУ'), ('PAID', 'ОПЛАЧЕНО'), ('COD', 'ОПЛАТА ПРИ ОТРИМАННІ')], default='COD', max_length=10, verbose_name='Оплата'),
        ),
    ]
