from contextlib import contextmanager
from typing import Any, Generator, Union

from aiogram_i18n import LazyProxy


class Languages:
    def uk(self) -> str: ...
    def en(self) -> str: ...
    def ru(self) -> str: ...

class Button:
    def profile(self) -> str: ...
    def products(self) -> str: ...
    def cart(self) -> str: ...
    def help(self) -> str: ...
    def change_language(self) -> str: ...
    def back(self) -> str: ...
    def for_as(self) -> str: ...
    def delivery(self) -> str: ...
    def pay(self) -> str: ...
    def add(self) -> str: ...

class User:
    def start_cmd(self) -> str: ...
    def language_changed(self) -> str: ...
    def choose_option(self) -> str: ...
    def product_ingredients(self) -> str: ...
    def product_nutrition(self) -> str: ...
    def empty_text(self) -> str: ...
    def gram(self) -> str: ...
    def added_to_cart(self) -> str: ...
    def choice_dlvr(self) -> str: ...
    def text_dlvr_glovo(self) -> str: ...

class I18nStubs:
    user = User()
    button = Button()
    languages = Languages()

class I18nContext(I18nStubs):
    def get(self, key: str, /, **kwargs: Any) -> str: ...
    async def set_locale(self, locale: str, **kwargs: Any) -> None: ...
    @contextmanager
    def use_locale(self, locale: str) -> Generator[I18nContext, None, None]: ...
    @contextmanager
    def use_context(self, **kwargs: Any) -> Generator[I18nContext, None, None]: ...
    def set_context(self, **kwargs: Any) -> None: ...

class LazyFactory(I18nStubs):
    key_separator: str
    def set_separator(self, key_separator: str) -> None: ...
    def __call__(self, key: str, /, **kwargs: dict[str, Any]) -> LazyProxy: ...

L: LazyFactory
