# Generated by Django 5.1.4 on 2026-02-25 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/images/', verbose_name='Зображення')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-адреса (slug)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('author', models.CharField(default='Zero Caloriy', max_length=100, verbose_name='Автор')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Назва (УКР)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва (ENG)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва (РУС)')),
                ('text_uk', models.TextField(verbose_name='Текст (УКР)')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст (ENG)')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст (РУС)')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-created_at'],
            },
        ),
    ]
