# Generated by Django 5.1.4 on 2026-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Зеро калорій', max_length=100, verbose_name='Автор'),
        ),
    ]
