# Generated by Django 5.1.4 on 2026-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст цитата (ENG)'),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст цитата (РУС)'),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст цитата (УКР)'),
        ),
    ]
