# Generated by Django 5.1.4 on 2026-03-11 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_quote_en_post_quote_ru_post_quote_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (ENG)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст (РУС)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_uk',
            field=ckeditor.fields.RichTextField(verbose_name='Текст (УКР)'),
        ),
    ]
